// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calc_pval
NumericVector calc_pval(NumericVector x, NumericVector y);
RcppExport SEXP lodscores_calc_pval(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    __result = Rcpp::wrap(calc_pval(x, y));
    return __result;
END_RCPP
}
// lod_scores
NumericMatrix lod_scores(NumericMatrix freqARR, NumericMatrix allARR, int num_ind, double k0, double k1);
RcppExport SEXP lodscores_lod_scores(SEXP freqARRSEXP, SEXP allARRSEXP, SEXP num_indSEXP, SEXP k0SEXP, SEXP k1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type freqARR(freqARRSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type allARR(allARRSEXP);
    Rcpp::traits::input_parameter< int >::type num_ind(num_indSEXP);
    Rcpp::traits::input_parameter< double >::type k0(k0SEXP);
    Rcpp::traits::input_parameter< double >::type k1(k1SEXP);
    __result = Rcpp::wrap(lod_scores(freqARR, allARR, num_ind, k0, k1));
    return __result;
END_RCPP
}
