# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_pval <- function(x, y) {
    .Call('lodscores_calc_pval', PACKAGE = 'lodscores', x, y)
}

lod_scores <- function(freqARR, allARR, num_ind, k0, k1) {
    .Call('lodscores_lod_scores', PACKAGE = 'lodscores', freqARR, allARR, num_ind, k0, k1)
}

